server:
  port: 8007
spring:
  application:
    name: Aop8007
  redis:
    database: 0 #Redis数据库索引（默认为0）
    host: 152.32.133.201 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    #password: 12456 # Redis服务器连接密码（默认为空）
