server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://152.32.133.201:3306/db2020?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.demo.entity #实体类对应包路径

#从这里看出如果是整合了RocketMQTemplate是不需要在代码里面注入这些配置的
rocketmq:
  name-server: 152.32.133.201:9876
  producer:
    group: springBootGroup