server:
  port: 8002

spring:
  application:
    name: cloud2020
  redis:
    database: 0 #Redis数据库索引（默认为0）
#    host: 152.32.133.201 # Redis服务器地址
    host: 127.0.0.1 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    #password: 12456 # Redis服务器连接密码（默认为空）
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8 # 连接池中的最大空闲连接 默认 8
        min-idle: 0 # 连接池中的最小空闲连接 默认 0

#从这里看出如果是整合了RocketMQTemplate是不需要在代码里面注入这些配置的
rocketmq:
  name-server: 152.32.133.201:9876
  producer:
    group: springBootGroup

